/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package studentDashboard;

import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import sessionAttributes.Student;
import mySQLConnection.MySQLConnection;
import com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException;

/**
 *
 * @author ACER AMD
 */
public class ProposalForm extends javax.swing.JFrame {

    JFileChooser fc;
    File cvFile, folioFile;
    FileNameExtensionFilter restrict;
    String tempNIM, tempName, tempDate, tempAddress, tempResult;

    /**
     * Creates new form ProposalForm
     */
    public ProposalForm() {
        initComponents();
        setResizable(false);
        addressTextArea.setLineWrap(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cvLabel = new javax.swing.JLabel();
        cvField = new javax.swing.JTextField();
        cvButton = new javax.swing.JButton();
        folioLabel = new javax.swing.JLabel();
        folioField = new javax.swing.JTextField();
        folioButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        addressLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        timeChooser = new com.toedter.calendar.JDateChooser();
        backButton = new javax.swing.JButton();
        submitButton = new javax.swing.JButton();
        timeLabel1 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(128, 1, 1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pengajuan Proposal");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20))
        );

        cvLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cvLabel.setText("Curiculum Vitae");

        cvField.setEditable(false);
        cvField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cvField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        cvButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        cvButton.setText("Attach File");
        cvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvButtonActionPerformed(evt);
            }
        });

        folioLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        folioLabel.setText("Portofolio");

        folioField.setEditable(false);
        folioField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        folioButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        folioButton.setText("Attach File");
        folioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folioButtonActionPerformed(evt);
            }
        });

        addressTextArea.setColumns(20);
        addressTextArea.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        addressTextArea.setRows(5);
        jScrollPane1.setViewportView(addressTextArea);

        addressLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        addressLabel.setText("Alamat PKN");

        timeLabel.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        timeLabel.setText("Waktu Pelaksanaan");

        timeChooser.setDateFormatString("dd-MM-yyyy");
        timeChooser.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        backButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        backButton.setText("Kembali");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        submitButton.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        timeLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        timeLabel1.setText("E-Mail Instansi");

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cvLabel)
                            .addComponent(folioLabel)
                            .addComponent(addressLabel)
                            .addComponent(timeLabel)
                            .addComponent(timeLabel1))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cvField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cvButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(emailField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeChooser, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(folioField, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(folioButton)))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(backButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitButton)))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cvButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(folioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(folioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(folioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(timeChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                    .addComponent(timeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel1)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(submitButton))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvButtonActionPerformed
        // TODO add your handling code here:
        fc = new JFileChooser();
        fc.setAcceptAllFileFilterUsed(false);
        restrict = new FileNameExtensionFilter("Only .pdf files", "pdf");
        fc.addChoosableFileFilter(restrict);
        int a = fc.showOpenDialog(null);
        if (a == JFileChooser.APPROVE_OPTION) {
            cvField.setText(fc.getSelectedFile().getAbsolutePath());
            cvFile = fc.getSelectedFile();
        }

    }//GEN-LAST:event_cvButtonActionPerformed

    private void folioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folioButtonActionPerformed
        // TODO add your handling code here:
        fc = new JFileChooser();
        fc.setAcceptAllFileFilterUsed(false);
        restrict = new FileNameExtensionFilter("Only .pdf files", "pdf");
        fc.addChoosableFileFilter(restrict);
        int a = fc.showOpenDialog(null);
        if (a == JFileChooser.APPROVE_OPTION) {
            folioField.setText(fc.getSelectedFile().getAbsolutePath());
            folioFile = fc.getSelectedFile();
        }
    }//GEN-LAST:event_folioButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        StudentMenu std = new StudentMenu();
        std.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        setData();
        try {
            Connection myConn = MySQLConnection.getConnection();
            String query = "INSERT INTO proposal (NIM, NAMA, WAKTU, TEMPAT, STATUS) VALUES ('"
                    + tempNIM + "','" + tempName + "','" + tempDate + "'," + "'"
                    + tempAddress + "', '" + tempResult + "')";
            PreparedStatement ps = myConn.prepareStatement(query);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Berhasil");
        } catch (MySQLIntegrityConstraintViolationException sqle) {
            JOptionPane.showMessageDialog(this, sqle.getMessage() + ", anda sudah mengajukan proposal.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        } finally {
            clear();
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void clear() {
        cvField.setText("");
        folioField.setText("");
        addressTextArea.setText("");
        timeChooser.setDateFormatString("");
        emailField.setText("");
    }

    private void setData() {
        tempNIM = Student.getNIM();
        tempName = Student.getName();
        tempDate = String.valueOf(timeChooser.getDate());
        tempAddress = addressTextArea.getText();
        tempResult = "Pending";
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProposalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProposalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProposalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProposalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProposalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JButton backButton;
    private javax.swing.JButton cvButton;
    private javax.swing.JTextField cvField;
    private javax.swing.JLabel cvLabel;
    private javax.swing.JTextField emailField;
    private javax.swing.JButton folioButton;
    private javax.swing.JTextField folioField;
    private javax.swing.JLabel folioLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitButton;
    private com.toedter.calendar.JDateChooser timeChooser;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JLabel timeLabel1;
    // End of variables declaration//GEN-END:variables
}
